server:
  port: 8080

spring:
  application:
    name: eshop-rest-api
  datasource:
    url: jdbc:mysql://mysql:3306/eshopdb?createDatabaseIfNotExist=true
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
